//! `sanctum scan`: scan mounted targets for malware and write a case report
//! (AV-1).
//!
//! - ClamAV runs as a clamd daemon for this scan only, with as many threads
//!   as CPUs, and `clamdscan --multiscan` walks the targets in parallel.
//! - On NTFS (mounted by `sanctum mount`, which exposes alternate data
//!   streams as extended attributes), every named stream is copied to a
//!   private runtime directory and scanned too: malware is often hidden
//!   there, where a plain file scan never looks.
//! - Each finding is hashed (SHA-256). The report (JSON and HTML), the raw
//!   ClamAV logs and the database versions go into a case directory on the
//!   data partition.
//!
//! The scan only reads. Nothing is moved, changed or deleted; removing
//! threats is a separate, deliberate step (quarantine, AV-2).

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};

use serde::Serialize;

use crate::clamav::{self, Database};
use crate::data;
use crate::paths;
use crate::sys;
use crate::term::{self, outln};

/// Larger alternate data streams are reported as not scanned.
const MAX_STREAM_BYTES: u64 = 400 * 1024 * 1024;

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct Finding {
    /// The file (for a stream: the file that carries it).
    pub(crate) path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) stream: Option<String>,
    pub(crate) signature: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) sha256: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) size: Option<u64>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ScannedTarget {
    pub(crate) path: String,
    pub(crate) source: String,
    pub(crate) fstype: String,
}

#[derive(Debug, Serialize)]
pub(crate) struct Report {
    pub(crate) tool: String,
    pub(crate) case: String,
    pub(crate) started: String,
    pub(crate) finished: String,
    pub(crate) targets: Vec<ScannedTarget>,
    pub(crate) engine: String,
    pub(crate) databases: Vec<Database>,
    pub(crate) streams_scanned: u64,
    pub(crate) findings: Vec<Finding>,
    pub(crate) errors: Vec<String>,
    /// clean, infected or incomplete
    pub(crate) result: String,
    pub(crate) persistent: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LineKind {
    Found,
    Error,
    Other,
}

/// Parse one `clamdscan --stdout` line: "PATH: SIGNATURE FOUND" or
/// "PATH: MESSAGE ERROR".
pub(crate) fn parse_line(line: &str) -> (LineKind, String, String) {
    for (suffix, kind) in [(" FOUND", LineKind::Found), (" ERROR", LineKind::Error)] {
        if let Some(rest) = line.strip_suffix(suffix)
            && let Some((path, what)) = rest.rsplit_once(": ")
        {
            return (kind, path.to_owned(), what.to_owned());
        }
    }
    (LineKind::Other, String::new(), line.to_owned())
}

/// Keep case names to safe characters.
pub(crate) fn safe_name(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || "._-".contains(c) {
                c
            } else {
                '-'
            }
        })
        .collect();
    let trimmed = cleaned.trim_matches(|c| c == '-' || c == '.');
    if trimmed.is_empty() {
        "scan".to_owned()
    } else {
        trimmed.to_owned()
    }
}

fn now_utc() -> String {
    sys::output_or_empty("date", &["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .trim()
        .to_owned()
}

fn cpu_count() -> usize {
    std::thread::available_parallelism().map_or(2, std::num::NonZero::get)
}

/// Detections (path, signature) and error messages from one clamdscan run.
type ScanOutput = (Vec<(String, String)>, Vec<String>);

/// A clamd started for this scan, stopped when dropped.
struct Clamd {
    child: Child,
    config: PathBuf,
}

impl Drop for Clamd {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

impl Clamd {
    fn start(db_dir: &Path, run: &Path, log: &Path, threads: usize) -> Result<Clamd, String> {
        let config = run.join("clamd.conf");
        let socket = run.join("clamd.sock");
        let _ = fs::remove_file(&socket);
        fs::write(
            &config,
            format!(
                "# Generated by sanctum scan.\n\
                 LocalSocket {}\n\
                 LocalSocketMode 600\n\
                 DatabaseDirectory {}\n\
                 Foreground yes\n\
                 MaxThreads {threads}\n\
                 MaxScanSize 1000M\n\
                 MaxFileSize 400M\n\
                 MaxRecursion 17\n\
                 MaxFiles 20000\n\
                 FollowDirectorySymlinks no\n\
                 FollowFileSymlinks no\n\
                 ExtendedDetectionInfo yes\n\
                 ConcurrentDatabaseReload no\n\
                 LogTime yes\n",
                socket.display(),
                db_dir.display()
            ),
        )
        .map_err(|e| format!("cannot write {}: {e}", config.display()))?;
        let logfile = fs::File::create(log).map_err(|e| e.to_string())?;
        let errfile = logfile.try_clone().map_err(|e| e.to_string())?;
        let child = Command::new("clamd")
            .arg(format!("--config-file={}", config.display()))
            .stdin(Stdio::null())
            .stdout(logfile)
            .stderr(errfile)
            .spawn()
            .map_err(|e| format!("cannot start clamd: {e}"))?;
        let clamd = Clamd { child, config };
        outln!("Loading ClamAV databases (this takes up to a minute)...");
        // Up to 300 attempts, one second apart.
        let ready = Command::new("clamdscan")
            .args([
                &format!("--config-file={}", clamd.config.display()),
                "--ping",
                "300:1",
            ])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .is_ok_and(|s| s.success());
        if ready {
            Ok(clamd)
        } else {
            Err(format!("clamd did not start; see {}", log.display()))
        }
    }

    /// Scan paths; returns (findings, errors) from the output.
    fn scan(&self, paths: &[PathBuf], log: &Path) -> Result<ScanOutput, String> {
        let out = Command::new("clamdscan")
            .arg(format!("--config-file={}", self.config.display()))
            .args(["--multiscan", "--infected", "--no-summary", "--stdout"])
            .args(paths)
            .stdin(Stdio::null())
            .output()
            .map_err(|e| format!("cannot run clamdscan: {e}"))?;
        let text = String::from_utf8_lossy(&out.stdout).into_owned();
        let mut previous = fs::read_to_string(log).unwrap_or_default();
        previous.push_str(&text);
        fs::write(log, previous).map_err(|e| e.to_string())?;
        let mut found = Vec::new();
        let mut errors = Vec::new();
        for line in text.lines() {
            match parse_line(line) {
                (LineKind::Found, path, sig) => found.push((path, sig)),
                (LineKind::Error, path, msg) => errors.push(format!("{path}: {msg}")),
                (LineKind::Other, _, _) => {}
            }
        }
        // Exit status 2 means an error that left no line to report.
        if out.status.code() == Some(2) && errors.is_empty() && found.is_empty() {
            errors.push(format!(
                "clamdscan failed: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            ));
        }
        Ok((found, errors))
    }
}

/// Filesystem type and source of the mount a path is on.
fn mount_info(path: &Path) -> (String, String) {
    let out = sys::output_or_empty(
        "findmnt",
        &[
            "--noheadings",
            "--output",
            "FSTYPE,SOURCE",
            "--target",
            &path.to_string_lossy(),
        ],
    );
    let mut parts = out.split_whitespace();
    (
        parts.next().unwrap_or("").to_owned(),
        parts.next().unwrap_or("").to_owned(),
    )
}

struct Stream {
    owner: PathBuf,
    name: String,
    copy: PathBuf,
}

/// Copy every named data stream under `root` (NTFS-3G, streams exposed as
/// user.* extended attributes) into `out_dir`.
fn extract_streams(root: &Path, out_dir: &Path, errors: &mut Vec<String>) -> Vec<Stream> {
    let mut streams = Vec::new();
    let mut pending = vec![root.to_path_buf()];
    let mut seen: u64 = 0;
    while let Some(path) = pending.pop() {
        let Ok(meta) = fs::symlink_metadata(&path) else {
            continue;
        };
        if meta.file_type().is_symlink() {
            continue;
        }
        seen += 1;
        if seen.is_multiple_of(20_000) {
            outln!("  {} checked for alternate data streams...", seen);
        }
        if let Ok(names) = xattr::list(&path) {
            for name in names {
                let name = name.to_string_lossy().into_owned();
                let Some(stream) = name.strip_prefix("user.") else {
                    continue;
                };
                match xattr::get(&path, &name) {
                    Ok(Some(bytes)) if (bytes.len() as u64) <= MAX_STREAM_BYTES => {
                        let copy = out_dir.join(format!("{}.stream", streams.len()));
                        match fs::write(&copy, &bytes) {
                            Ok(()) => streams.push(Stream {
                                owner: path.clone(),
                                name: stream.to_owned(),
                                copy,
                            }),
                            Err(e) => errors.push(format!(
                                "{}:{stream}: cannot copy stream: {e}",
                                path.display()
                            )),
                        }
                    }
                    Ok(Some(_)) => errors.push(format!(
                        "{}:{stream}: stream larger than 400 MiB, not scanned",
                        path.display()
                    )),
                    Ok(None) => {}
                    Err(e) => errors.push(format!(
                        "{}:{stream}: cannot read stream: {e}",
                        path.display()
                    )),
                }
            }
        }
        if meta.is_dir() {
            match fs::read_dir(&path) {
                Ok(entries) => pending.extend(entries.flatten().map(|e| e.path())),
                Err(e) => errors.push(format!("{}: {e}", path.display())),
            }
        }
    }
    streams
}

fn html_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

pub(crate) fn render_html(r: &Report) -> String {
    let (verdict, colour) = match r.result.as_str() {
        "clean" => ("No threats found", "#3fb950"),
        "infected" => ("Threats found", "#f85149"),
        _ => ("Scan incomplete", "#d29922"),
    };
    let mut h = format!(
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Sanctum scan {case}</title>\n<style>\
body{{margin:0;background:#0b0e14;color:#d6dbe4;font:15px/1.5 'DejaVu Sans',sans-serif}}main{{max-width:64rem;margin:0 auto;padding:1.5rem 1rem}}\
h1{{font-size:1.5rem}}.verdict{{font-size:1.3rem;font-weight:bold;color:{colour}}}table{{border-collapse:collapse;width:100%;margin:.5rem 0 1.5rem}}\
th,td{{border:1px solid #232a36;padding:.35rem .5rem;text-align:left;vertical-align:top}}th{{background:#141922}}code{{font-family:'DejaVu Sans Mono',monospace;font-size:.9em;word-break:break-all}}\
.muted{{color:#8b93a3}}</style></head><body><main>\n<h1>Abyssal Sanctum scan report</h1>\n<p class=\"verdict\">{verdict}</p>\n<table>\
<tr><th>Case</th><td><code>{case}</code></td></tr><tr><th>Started</th><td>{started}</td></tr><tr><th>Finished</th><td>{finished}</td></tr>\
<tr><th>Engine</th><td>{engine}</td></tr><tr><th>Tool</th><td>{tool}</td></tr><tr><th>Alternate data streams scanned</th><td>{streams}</td></tr></table>\n",
        case = html_escape(&r.case),
        started = html_escape(&r.started),
        finished = html_escape(&r.finished),
        engine = html_escape(&r.engine),
        tool = html_escape(&r.tool),
        streams = r.streams_scanned,
    );
    h.push_str(
        "<h2>Targets</h2>\n<table><tr><th>Path</th><th>Device</th><th>Filesystem</th></tr>\n",
    );
    for t in &r.targets {
        let _ = writeln!(
            h,
            "<tr><td><code>{}</code></td><td><code>{}</code></td><td>{}</td></tr>",
            html_escape(&t.path),
            html_escape(&t.source),
            html_escape(&t.fstype)
        );
    }
    let _ = writeln!(h, "</table>\n<h2>Findings ({})</h2>", r.findings.len());
    if r.findings.is_empty() {
        h.push_str("<p>None.</p>\n");
    } else {
        h.push_str("<table><tr><th>File</th><th>Stream</th><th>Detection</th><th>SHA-256</th><th>Size</th></tr>\n");
        for f in &r.findings {
            let _ = writeln!(
                h,
                "<tr><td><code>{}</code></td><td>{}</td><td>{}</td><td><code>{}</code></td><td>{}</td></tr>",
                html_escape(&f.path),
                f.stream.as_deref().map(html_escape).unwrap_or_default(),
                html_escape(&f.signature),
                f.sha256.as_deref().unwrap_or(""),
                f.size.map(|s| s.to_string()).unwrap_or_default()
            );
        }
        h.push_str("</table>\n");
    }
    h.push_str("<h2>Databases</h2>\n<table><tr><th>File</th><th>Version</th><th>Built</th><th>Signatures</th></tr>\n");
    for d in &r.databases {
        let _ = writeln!(
            h,
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            html_escape(&d.file),
            html_escape(d.version.as_deref().unwrap_or(&d.kind)),
            html_escape(d.build_time.as_deref().unwrap_or("")),
            d.signatures.map(|s| s.to_string()).unwrap_or_default()
        );
    }
    h.push_str("</table>\n");
    if !r.errors.is_empty() {
        let _ = writeln!(h, "<h2>Errors ({})</h2>\n<ul>", r.errors.len());
        for e in &r.errors {
            let _ = writeln!(h, "<li><code>{}</code></li>", html_escape(e));
        }
        h.push_str("</ul>\n");
    }
    h.push_str("<p class=\"muted\">The scan only read the targets. Nothing was moved, changed or deleted.</p>\n</main></body></html>\n");
    h
}

/// Run a scan. Returns the exit code: 0 clean, 1 threats found, 2 the scan
/// was incomplete.
pub(crate) fn run(targets: &[PathBuf], case: Option<&str>, streams: bool) -> Result<u8, String> {
    sys::require_root()?;
    if targets.is_empty() {
        return Err(
            "name at least one directory to scan, for example a mount from `sanctum mount`"
                .to_owned(),
        );
    }
    for t in targets {
        if !t.is_dir() && !t.is_file() {
            return Err(format!("{} does not exist", t.display()));
        }
    }
    let ws = data::workspace();
    data::warn_if_volatile(&ws);
    let databases = clamav::databases(&ws)?;
    if databases.is_empty() {
        return Err("no ClamAV databases: run `sanctum update` (online) or `sanctum update --import PACK` first".to_owned());
    }
    if let Some(warning) = clamav::stale_warning(&databases) {
        outln!("{}", term::caution(&warning));
    }

    let started = now_utc();
    let stamp = started.replace([':', '-'], "");
    let case_id = format!(
        "{}-{}",
        stamp.trim_end_matches('Z'),
        safe_name(case.unwrap_or("scan"))
    );
    let case_dir = ws.dir("cases")?.join(&case_id);
    fs::create_dir_all(&case_dir)
        .map_err(|e| format!("cannot create {}: {e}", case_dir.display()))?;
    let run_dir = paths::run_dir().join("scan").join(&case_id);
    let _ = fs::remove_dir_all(&run_dir);
    fs::create_dir_all(&run_dir).map_err(|e| e.to_string())?;
    outln!("Case {} in {}", term::bold(&case_id), case_dir.display());

    let threads = cpu_count();
    let engine = sys::output_or_empty("clamd", &["--version"])
        .trim()
        .to_owned();
    let clamd = Clamd::start(
        &clamav::database_dir(&ws)?,
        &run_dir,
        &case_dir.join("clamd.log"),
        threads,
    )?;
    let scan_log = case_dir.join("clamdscan.log");

    let mut scanned = Vec::new();
    let mut findings = Vec::new();
    let mut errors = Vec::new();
    let mut stream_count = 0u64;
    let absolute: Vec<PathBuf> = targets
        .iter()
        .map(|t| fs::canonicalize(t).unwrap_or_else(|_| t.clone()))
        .collect();

    outln!(
        "Scanning {} with {threads} threads...",
        absolute
            .iter()
            .map(|p| p.display().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    );
    let (found, errs) = clamd.scan(&absolute, &scan_log)?;
    errors.extend(errs);
    for (path, signature) in found {
        let p = Path::new(&path);
        findings.push(Finding {
            path: path.clone(),
            stream: None,
            signature,
            sha256: sys::sha256_file(p).ok(),
            size: fs::metadata(p).map(|m| m.len()).ok(),
        });
    }

    for target in &absolute {
        let (fstype, source) = mount_info(target);
        if streams && fstype == "fuseblk" {
            outln!(
                "Checking {} for alternate data streams...",
                target.display()
            );
            let dir = run_dir.join(format!("streams-{}", scanned.len()));
            fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
            let extracted = extract_streams(target, &dir, &mut errors);
            stream_count += extracted.len() as u64;
            if !extracted.is_empty() {
                let (found, errs) = clamd.scan(std::slice::from_ref(&dir), &scan_log)?;
                errors.extend(errs);
                for (copy, signature) in found {
                    if let Some(s) = extracted.iter().find(|s| s.copy.to_string_lossy() == copy) {
                        findings.push(Finding {
                            path: s.owner.to_string_lossy().into_owned(),
                            stream: Some(s.name.clone()),
                            signature,
                            sha256: sys::sha256_file(&s.copy).ok(),
                            size: fs::metadata(&s.copy).map(|m| m.len()).ok(),
                        });
                    }
                }
            }
            let _ = fs::remove_dir_all(&dir);
        }
        scanned.push(ScannedTarget {
            path: target.to_string_lossy().into_owned(),
            source,
            fstype,
        });
    }
    drop(clamd);
    let _ = fs::remove_dir_all(&run_dir);

    let result = if !findings.is_empty() {
        "infected"
    } else if !errors.is_empty() {
        "incomplete"
    } else {
        "clean"
    };
    let report = Report {
        tool: format!("Abyssal Sanctum {}", env!("CARGO_PKG_VERSION")),
        case: case_id,
        started,
        finished: now_utc(),
        targets: scanned,
        engine,
        databases,
        streams_scanned: stream_count,
        findings,
        errors,
        result: result.to_owned(),
        persistent: ws.persistent,
    };
    let json = serde_json::to_string_pretty(&report).map_err(|e| e.to_string())?;
    fs::write(case_dir.join("report.json"), json + "\n").map_err(|e| e.to_string())?;
    fs::write(case_dir.join("report.html"), render_html(&report)).map_err(|e| e.to_string())?;

    outln!();
    for f in &report.findings {
        let what = f.stream.as_ref().map_or_else(
            || f.path.clone(),
            |s| format!("{}:{s} (alternate data stream)", f.path),
        );
        outln!("  {}  {}", term::bad(&f.signature), what);
    }
    outln!(
        "\n{}: {} finding(s), {} error(s), {} stream(s) scanned.",
        match result {
            "clean" => term::good("Clean"),
            "infected" => term::bad("Threats found"),
            _ => term::caution("Incomplete"),
        },
        report.findings.len(),
        report.errors.len(),
        report.streams_scanned
    );
    outln!("Report: {}", case_dir.join("report.html").display());
    outln!("{}", term::dim("Nothing was moved, changed or deleted."));
    Ok(match result {
        "clean" => 0,
        "infected" => 1,
        _ => 2,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_clamdscan_lines() {
        assert_eq!(
            parse_line("/mnt/sanctum/sda3/Users/a/x.com: Eicar-Test-Signature FOUND"),
            (
                LineKind::Found,
                "/mnt/sanctum/sda3/Users/a/x.com".to_owned(),
                "Eicar-Test-Signature".to_owned()
            )
        );
        assert_eq!(
            parse_line("/mnt/a: weird: name.exe: Win.Trojan.X FOUND"),
            (
                LineKind::Found,
                "/mnt/a: weird: name.exe".to_owned(),
                "Win.Trojan.X".to_owned()
            )
        );
        assert_eq!(
            parse_line("/mnt/b: Access denied. ERROR").0,
            LineKind::Error
        );
        assert_eq!(
            parse_line("----------- SCAN SUMMARY -----------").0,
            LineKind::Other
        );
    }

    #[test]
    fn case_names_are_sanitised() {
        assert_eq!(safe_name("ACME laptop #3"), "ACME-laptop--3");
        assert_eq!(safe_name("../../etc"), "etc");
        assert_eq!(safe_name("   "), "scan");
    }

    #[test]
    fn html_report_escapes_paths() {
        let r = Report {
            tool: "t".into(),
            case: "c".into(),
            started: "s".into(),
            finished: "f".into(),
            targets: vec![],
            engine: "ClamAV".into(),
            databases: vec![],
            streams_scanned: 1,
            findings: vec![Finding {
                path: "/mnt/<script>.exe".into(),
                stream: Some("payload".into()),
                signature: "Eicar".into(),
                sha256: None,
                size: None,
            }],
            errors: vec![],
            result: "infected".into(),
            persistent: true,
        };
        let html = render_html(&r);
        assert!(html.contains("&lt;script&gt;.exe"));
        assert!(!html.contains("<script>.exe"));
        assert!(html.contains("Threats found"));
    }
}
